version: '3.8'

services:
  ai-test-automation:
    build: .
    container_name: ai-test-automation
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app/src
      - DISPLAY=:99
    depends_on:
      - ollama
    networks:
      - ai-network
    command: ["python", "main.py", "--help"]

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  # Optional: Web interface for Ollama
  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    volumes:
      - ollama_webui_data:/app/backend/data
    networks:
      - ai-network
    restart: unless-stopped

volumes:
  ollama_data:
  ollama_webui_data:

networks:
  ai-network:
    driver: bridge 